# pip install -U ruff uv ty pre-commit
# pre-commit install
# pre-commit install --hook-type commit-msg
# pre-commit autoupdate
# pre-commit run --all-files
# pre-commit run --files "sys_setup/windows/main.py"

# More info about conventional commits here:
# https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

repos:
  # Basic ones
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        types: [markdown, python]
        files: "\\.(md|py)$"

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # Opt: list of Conv Commits types to allow like: ci,fix..
