[project]
name = "silksong-rosary-farmer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "egeres", email = "egeres.default@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
silksong-rosary-farmer = "silksong_rosary_farmer:main"

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"
